version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: "compose-nginx1"
        restart: always
        ports:
            - "8002:80"
        environment:
           - TZ=Asia/Shanghai
        volumes:
           - "./nginx.conf:/etc/nginx/nginx.conf"
