FROM python:3.7-alpine

COPY ./files /app

COPY ./flag /flag

RUN pip install --default-timeout=100  -i https://pypi.tuna.tsinghua.edu.cn/simple -r app/requirements.txt 

WORKDIR /app

CMD  python app.py