version: "3"
services:
  app:
    image: ctfhub/base_web_nginx_mysql_php_56:latest
    container_name: "ssrf"
    ports:
      - 8349:80
    volumes:
      - "./html:/var/www/html"
      - "./flag:/flag"