version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: "compose-nginx4"
        restart: always
        ports:
            - "8004:80"
        environment:
           - TZ=Asia/Shanghai
        depends_on:
           - "php"
        volumes:
           - "./default.conf:/etc/nginx/conf.d/default.conf"
           - "./html:/usr/share/nginx/html"
        networks:
           - net-app2
    php:
        image: php:7.4-fpm
        container_name: "compose-php2"
        restart: always
        ports:
            - "9124:9000"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "./html:/usr/share/nginx/html"
            - "./php.ini:/usr/local/etc/php/php.ini"
            - "./flag:/flag"
        networks:
           - net-app2

networks:
    net-app2: