version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: "compose-nginx-pop"
        restart: always
        ports:
            - "8123:80"
        environment:
           - TZ=Asia/Shanghai
        depends_on:
           - "php"
        volumes:
           - "./default.conf:/etc/nginx/conf.d/default.conf"
           - "./www:/usr/share/nginx/html"
        networks:
           - net-app
    php:
        image: php:7.4-fpm
        container_name: "compose-php-pop"
        restart: always
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - "./www:/usr/share/nginx/html"
            - "./php.ini:/usr/local/etc/php/php.ini"
        networks:
           - net-app

networks:
    net-app: