version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: "compose-nginx2"
        restart: always
        ports:
            - "8001:80"
        environment:
           - TZ=Asia/Shanghai
        volumes:
           - "./nginx.conf:/etc/nginx/nginx.conf"
           - "./html:/usr/share/nginx/html"
