FROM nginx
COPY nginx.conf /etc/nignx/nginx.conf
RUN echo '<h2>Where is my Robots?<h2>' > /usr/share/nginx/html/index.html \
    && echo 'flag in FFFFl3gggg.txt' > /usr/share/nginx/html/robots.txt \
    && echo '0xGame{We1c0me!_Th1s_is_Your_Fl3g}' > /usr/share/nginx/html/FFFFl3gggg.txt